version: '2'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: pokemon
      MYSQL_PASSWORD: pokemon
      MYSQL_DATABASE: pokemon
      MYSQL_ROOT_PASSWORD: pokemon
